# Mengizinkan akses tanpa password secara global
allow_anonymous true

# ==========================================
# JALUR 1: Untuk Script Node.js (Terminal)
# ==========================================
listener 1883
protocol mqtt
allow_anonymous true

# ==========================================
# JALUR 2: Untuk Dashboard HTML (Browser)
# ==========================================
listener 9001
protocol websockets
allow_anonymous true

# Log untuk memudahkan pemantauan
log_type error
log_type warning
log_type notice
log_type information